package com.mechcell.nomad.dymo_printing_service.utils

const val ACTION_REQUEST_PRINTERS = "DYMO_ACTION_REQUEST_PRINTERS"

const val ACTION_PROVIDE_PRINTERS = "DYMO_ACTION_PROVIDE_PRINTERS"

const val ACTION_SELECT_PRINTER = "DYMO_ACTION_SELECT_PRINTER"

const val PRINTERS_EXTRA = "DYMO_PRINTERS_EXTRA"

const val PRINTER_ID_EXTRA = "DYMO_PRINTER_ID_EXTRA"

const val PRINTER_NAME_EXTRA = "DYMO_PRINTER_NAME_EXTRA"

const val PRINTER_IP_EXTRA = "DYMO_PRINTER_IP_EXTRA"

const val PRINTER_PORT_EXTRA = "DYMO_PRINTER_PORT_EXTRA"

const val SELECTED_PRINTER_EXTRA = "DYMO_SELECTED_PRINTER_EXTRA"

const val PRINTER_NAME_PREF = "DYMO_PRINTER_NAME_PREF"

const val PRINTER_IP_PREF = "DYMO_PRINTER_IP_PREF"

const val PRINTER_PORT_PREF = "DYMO_PRINTER_PORT_PREF"

const val PRINTER_ADDED_PREF = "DYMO_PRINTER_ADDED_PREF"